### ISSUE TITLE
Issues with formats

### ISSUE THREAD

**Issue by Vaela-V** [TCDG/Apollo-Discord-Bot#1]
Hi, not sure whether you're still supporting this but I seem to be having an issue regarding getting the helpessage to send, I have no idea what's wrong but I'll put the error message down below. By any chance do you know how I could fix this please? Many thanks in advance!

`bot.py:83: DeprecationWarning: change_status is deprecated, use change_presence instead.
  await bot.change_status(game=discord.Game(name="%help | v.1.5"), idle=False)
Ignoring exception in on_server_join
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "bot.py", line 111, in on_server_join
    so that I can run my commands and functions properly!")
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 198, in request
    raise NotFound(r, data)
discord.errors.NotFound: NOT FOUND (status code: 404): Unknown Channel`

**Comment by mooncos** [comment]
Oh this is just that this project uses a very old dependency of the Discord API and the methods have been deprecated. I’m no longer supporting this project but I will make an exception! I’ll be updating it in the following days.

**Comment by Vaela-V** [comment]
Wow, thanks lots! :D I look forward to seeing the end product and will try it out whenever it's ready. :D
